version: '3.7'

volumes:
  mysql-data:
    driver: local
  mysql-data-test:
    driver: local

services:
  server:
    build: ./docker/php
    depends_on:
      - database
    volumes:
      - .:/var/www/html
      - ./logs/app.log:/tmp/app.log
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
  nginx:
    build: ./docker/nginx
    depends_on:
      - server
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  database:
    build: ./docker/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshop
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  database_test:
    build: ./docker/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookshop
    volumes:
      - mysql-data-test:/var/lib/mysql
      - ./docker/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
